from cos_values_gen import cos_fp, cos_divs, cos_values, cos_width

print("#pragma once")
print("// Generated by gen_cos_array.py");
print("#include <cstdint>")

print("namespace cos_values {")
print(f"static constexpr uint32_t fp = {cos_fp};")
print(f"static constexpr uint32_t divs = {cos_divs};")
print(f"static constexpr uint32_t width = {cos_width};")

# Pack coefficients into word array
print("// uint32_t data[] = {0x0aaabbbb, 0x0bbccccc};")
print(f"uint32_t data[{2 * cos_divs}] =")

first = True
for (a, b, c) in cos_values:
	if a > 0xfff:
		raise Exception(f"Overflow on a = {hex(a)}")
	if b > 0xffffff:
		raise Exception(f"Overflow on b = {hex(b)}")
	if c > 0xfffff:
		raise Exception(f"Overflow on c = {hex(c)}")

	d0 = (a << 16) | (b >> 8)
	d1 = ((b & 0xff) << 20) | c

	print(f"// a = {hex(a)}, b = {hex(b)}, c = {hex(c)}")
	delim = "{" if first else ","
	print(f"{delim} {hex(d0)}, {hex(d1)}")
	first = False

print("};")
print("}")
